### ISSUE TITLE
`lein new empty` still creates old version

### ISSUE THREAD

**Issue by razzius** [radian-software/empty#2]
Hi, me again! I updated the clojure version in this PR: #1, however I never tested that change out until just now.

When I ran `lein new empty`, I still got the 1.8.0 version in `project.clj`. Looking at https://clojars.org/empty/lein-template, it appears Clojars only has an old version of this repository (https://github.com/radian-software/empty/tree/8985051e81fc1c798a78b7440dcc45ee564d3439).

Could you push the latest of this repository to Clojars?

**Comment by raxod502** [comment]
Done!
